### ISSUE TITLE
Don't have a code issue but rather a library issue

### ISSUE THREAD

**Issue by VManning** [novichkov-lab/fama#2]
Hello,
I have used FAMA through Kbase. Awesome! Question: What is the NarC library (Respiratory nitrate reductase subunit, conjectural (EC 1.7.99.4)) based on. It is not similar to NarC in the dissimilatory nitrate reductase operon.

Thanks! Viola

**Comment by aekazakov** [comment]
Hi Viola,

The reference library for nitrogen-related enzymes is based on SEED (mostly) and KEGG annotations with some additional manual curation. NarC is the short name for SEED functional role "Respiratory nitrate reductase subunit, conjectural (EC 1.7.99.4)" (for the reference, see https://pubseed.theseed.org/SubsysEditor.cgi?page=ShowFunctionalRoles&subsystem=Nitrate_and_nitrite_ammonification), and this designation is kept in Fama for compatibility with SEED.
But you correctly state that the _narC_ gene in the haloarcheal operon is different from the SEED gene annotated as conjectural subunit (also called ORF7 in several articles).
