### ISSUE TITLE
Missing project.ini file

### ISSUE THREAD

**Issue by gaferguz** [novichkov-lab/fama#3]
Hi there, I would like to try this code with my Illumina read dataset for the first time, but unfortunately I cannot find any available template for project.ini file, which is suppossed to be located at py/ directory according to README.txt. 

Is it possible that you could you provide this file or copy its content on here?

Thanks in advance. Gabriel

**Comment by aekazakov** [comment]
See project.ini.sample file in the project folder.
Alternatively, you can use py/fama_prepare.py script with the '--notrim' option to generate project.ini.
