### ISSUE TITLE
error when running fama.py

### ISSUE THREAD

**Issue by camillaln** [novichkov-lab/fama#5]
Hi,

I got the databases downloaded - but get an error when I try to run the pipeline. 
It seems to be an issue with diamond parser?
I see there are test files in the t folder - however I cant figure out exactly how to run them. I would really appreciate some help with this - thanks!!

Camilla

python3 py/fama.py -c config.ini -p project_nitrogen_v10.ini
Running functional profiling for all samples in the project
Loading  /home/norquest/data/Camilla/fama/refdata/fama_nitrogen-cycle_v.10.0_functions_thresholds.tsv
54  functions found
Loading  /home/norquest/data/Camilla/fama/refdata/fama_nitrogen-cycle_v.10.0_proteins.txt
135664  reference proteins found
Loading taxonomy file /home/norquest/data/Camilla/fama/refdata/fama_nitrogen-cycle_v.10.0_taxonomy.tsv
Length cutoff: 15
Length cutoff: 15
Reading FASTQ file
Hits for forward end reads exported in FASTQ format
List of hits fo forward end reads exported
Classification DB search finished
Relative bit-score cutoff: 0.03 , Length cutoff: 15
Classification DB search results imported
Classified forward end reads exported in FASTQ format
Paired reads for classified forward end reads exported
Classified forward end reads exported in JSON format
Text report for forward end reads created
Traceback (most recent call last):
  File "/home/norquest/data/Camilla/fama/py/fama.py", line 58, in <module>
    main()
  File "/home/norquest/data/Camilla/fama/py/fama.py", line 48, in main
    fastq_pe_pipeline(
  File "/home/norquest/data/Camilla/fama/py/lib/pe_functional_pipeline.py", line 265, in fastq_pe_pipeline
    run_pe_fastq_pipeline(project,
  File "/home/norquest/data/Camilla/fama/py/lib/pe_functional_pipeline.py", line 376, in run_pe_fastq_pipeline
    generate_pdf_report(parser1)
  File "/home/norquest/data/Camilla/fama/py/lib/output/pdf_report.py", line 130, in generate_pdf_report
    pdf.write_html('\n'.join(table_rows))
  File "/home/norquest/miniconda3/envs/diamond/lib/python3.10/site-packages/fpdf/html.py", line 400, in write_html
    text = h2p.unescape(text) # To deal with HTML entities
AttributeError: 'HTML2FPDF' object has no attribute 'unescape'

**Comment by aekazakov** [comment]
Hi Camilla,

I can reproduce this error in python3.10. It looks like incompatibility of PyFPDF library and Python3 HTMLParser. 
I recommend making a new conda environment for Fama with python3.8 like this:

conda create -y -n env-fama python=3.8
conda activate env-fama
conda install -y diamond krona
git clone https://github.com/novichkov-lab/fama.git
cd fama
pip install -r requirements.txt
/bin/sh install_reference_data.sh
conda deactivate

**Comment by camillaln** [comment]
Thanks!
That works :)
Camilla
