### ISSUE TITLE
can't download http://iseq.lbl.gov/mydocs/fama_downloads/fama1_taxonomy.tar.gz

### ISSUE THREAD

**Issue by a-h-b** [novichkov-lab/fama#6]
Hi!
I've been trying to install FAMA, but the download of http://iseq.lbl.gov/mydocs/fama_downloads/fama1_taxonomy.tar.gz fails. Apparently, the link is stale. Can you take a look for me please?
Thanks in advance - Anna

**Comment by aekazakov** [comment]
The link should work now.
Sorry for the inconvenience.

**Comment by a-h-b** [comment]
cool thanks, works!
